name: Get Version
description: Get version number in project metadata

runs:
  using: "composite"
  steps:
  - name: Checkout repository
    uses: actions/checkout@v4.1.1

  - name: Set up Python
    uses: actions/setup-python@v5.0.0
    with:
      python-version: "3.10"

  - name: Install dependencies
    shell: bash
    run: |
      pip install toml

  - name: Extract version
    shell: bash
    run: |
      VERSION=$(python -c "import toml; print(toml.load(open('pyproject.toml'))['project']['version'])")
      echo "Version number: $VERSION."
      echo "XDCHECKIN_VERSION=$VERSION" >> $GITHUB_ENV
    working-directory: ${{ github.workspace }}
