name: Build Packages

on:
  workflow_call:
  workflow_dispatch:

jobs:
  build-android:
    name: Build for Android
    uses: Pairman/Xdcheckin/.github/workflows/build-android.yml@main
    secrets: inherit

  build-fedora:
    name: Build for Fedora
    uses: Pairman/Xdcheckin/.github/workflows/build-fedora.yml@main

  build-ubuntu:
    name: Build for Ubuntu
    uses: Pairman/Xdcheckin/.github/workflows/build-ubuntu.yml@main

  build-wheel:
    name: Build Python Wheel
    uses: Pairman/Xdcheckin/.github/workflows/build-wheel.yml@main

  build-windows:
    name: Build for Windows
    uses: Pairman/Xdcheckin/.github/workflows/build-windows.yml@main
