name: Build for Ubuntu

on:
  workflow_call:
  workflow_dispatch:

jobs:
  build-ubuntu:
    name: Build for Ubuntu
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4.1.1

    - name: Set up Python
      uses: actions/setup-python@v5.0.0
      with:
        python-version: "3.10"
        cache: pip

    - name: Install dependencies
      run: |
        sudo apt install -y libcairo2-dev libgirepository1.0-dev
        pip install briefcase toga

    - name: Build package
      run: |
        briefcase package
      working-directory: ${{ github.workspace }}

    - name: Upload package
      uses: actions/upload-artifact@v4.3.1
      with:
        if-no-files-found: error
        name: dist_ubuntu
        path: |
          dist/*.deb
