name: Build Packages

on:
  workflow_call:
  workflow_dispatch:

jobs:
  build-android:
    name: Build for Android
    uses: ./.github/workflows/build-android.yml
    secrets: inherit

  build-fedora:
    name: Build for Fedora
    uses: ./.github/workflows/build-fedora.yml

  build-ubuntu:
    name: Build for Ubuntu
    uses: ./.github/workflows/build-ubuntu.yml

  build-wheel:
    name: Build Python Wheel
    uses: ./.github/workflows/build-wheel.yml

  build-windows:
    name: Build for Windows
    uses: ./.github/workflows/build-windows.yml
