name: Check Version

on:
  workflow_call:
    outputs:
      version:
        description: The current version in project metadata
        value: ${{ jobs.check_version.outputs.version }}
      version_change:
        description: Whether the version changed in the last commit
        value: ${{ jobs.check_version.outputs.version_change }}

  workflow_dispatch:

jobs:
  check_version:
    name: Check Version
    runs-on: ubuntu-latest

    outputs:
      version: ${{ steps.check_version.outputs.version }}
      version_change: ${{ steps.check_version.outputs.version_change }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4.1.1
      with:
        fetch-depth: 2

    - name: Set up Python
      uses: actions/setup-python@v5.0.0
      with:
        python-version: "3.10"
        cache: pip

    - name: Install dependencies
      run: |
        pip install toml

    - name: Read and check for version increment
      id: check_version
      run: |
        version=$(python -c "from toml import load; print(load(open('pyproject.toml'))['project']['version'])")
        git checkout HEAD^
        version_prev=$(python -c "from toml import load; print(load(open('pyproject.toml'))['project']['version'])")
        version_change=false
        [[ "$version" != "$version_prev" ]] && version_change=true
        echo "Version: $version_prev -> $version, changed: $version_change."
        echo "version=$version" >> $GITHUB_OUTPUT
        echo "version_change=$version_change" >> $GITHUB_OUTPUT
      working-directory: ${{ github.workspace }}