name: Get Version Number in Project Metadata

on:
  workflow_dispatch:

jobs:
  build_ubuntu:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4.1.1

    - name: Set up Python
      uses: actions/setup-python@v5.0.0
      with:
        python-version: 3.10

    - name: Install dependencies
      run: |
        pip install toml

    - name: Extract version
      run: |
        VERSION=$(python -c "import toml; print(toml.load(open('pyproject.toml'))['project']['version'])")
        echo "Version extracted: $VERSION."
        echo "XDCHECKIN_VERSION=$VERSION" >> $GITHUB_ENV
      working-directory: ${{ github.workspace }}
