name: Force Build and Release

on:
  push:
    branches:
      - main
    paths:
      - pyproject.toml
  workflow_dispatch:

concurrency: 
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-wheel:
    name: Build Wheel
    uses: ./.github/workflows/build-wheel.yml
    secrets: inherit

  publish:
    name: Publish to PyPI
    runs-on: ubuntu-latest
    needs: build-wheel
    environment:
      name: publish-pypi
      url: https://pypi.org/project/Xdcheckin
    permissions:
      id-token: write

    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4.1.4
        with:
          name: dist_wheel
  
      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: ${{ inputs.working-directory }}/dist_wheel/
