name: Build and Release

on:
  push:
    branches:
      - main
    paths:
      - pyproject.toml
  workflow_dispatch:

concurrency: 
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  check-version:
    name: Check for version increment
    uses: ./.github/workflows/check-version.yml

  build:
    name: Build packages
    uses: ./.github/workflows/build.yml
    needs: check-version
    secrets: inherit
    if: ${{ needs.check_version.outputs.version_change == 'true' }}

  release:
    name: Release to GitHub
    runs-on: ubuntu-latest
    needs:
      - check-version
      - build

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.1.1

      - name: Download artifacts
        uses: actions/download-artifact@v4.1.4

      - name: Extract Release Notes
        id: extract-release-notes
        uses: ffurrer2/extract-release-notes@v2.1.0

      - name: Release to GitHub
        uses: softprops/action-gh-release@v2.0.2
        with:
          token: ${{ secrets.GH_TOKEN_RELEASES }}
          tag_name: ${{ needs.check-version.outputs.version }}
          name: ${{ needs.check-version.outputs.version }}
          body: ${{ steps.extract-release-notes.outputs.release_notes }}
          files: |
            dist_android/*.apk
            dist_fedora/*.rpm
            dist_ubuntu/*.deb
            dist_windows/*.msi

  publish:
    name: Publish to PyPI
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: publish-pypi
      url: https://pypi.org/project/Xdcheckin
    permissions:
      id-token: write

    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4.1.4
        with:
          name: dist_wheel
  
      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1.8
