name: Build and Release

on:
  push:
    paths: |
      **/pyproject.toml
  workflow_dispatch:

concurrency: 
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - name: Get version
      uses: Pairman/Xdcheckin/.github/actions/get-version@main

    - name: Test get version
      run: |
        echo $XDCHECKIN_VERSION

    - name: Create dummy file
      run: |
        echo $XDCHECKIN_VERSION >> dummy.log

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: dummy-${{ env.XDCHECKIN_VERSION }}.log
        path: dummy.log
