name: Build and Release

on:
  push:
    branches:
      - main
    paths:
      - pyproject.toml
  workflow_dispatch:

concurrency: 
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  check_version:
    name: Check for version increment
    uses: Pairman/Xdcheckin/.github/workflows/check-version.yml@main

  build:
    name: Build packages
    uses: Pairman/Xdcheckin/.github/workflows/build.yml@main
    needs: check_version
    secrets: inherit
    if: ${{ needs.check_version.outputs.version_change == 'true' }}

  release:
    name: Release to GitHub
    runs-on: ubuntu-latest
    needs:
      - check_version
      - build

    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4.1.4

      - name: Release to GitHub
        uses: softprops/action-gh-release@v2.0.2
        with:
          token: ${{ secrets.GH_TOKEN_RELEASES }}
          tag_name: ${{ needs.check_version.outputs.version }}
          name: ${{ needs.check_version.outputs.version }}
          body: Placeholder for upcoming release note.
          make_latest: false
          files: |
            dist_android/*.apk
            dist_fedora/*.rpm
            dist_ubuntu/*.deb
            dist_windows/*.msi
        env:
          GITHUB_REPOSITORY: Pairman/Xdcheckin

  publish:
    name: Publish to PyPI
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: publish-pypi
      url: https://pypi.org/project/Xdcheckin
    permissions:
      id-token: write

    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4.1.4
        with:
          name: dist_wheel
  
      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: dist_wheel/
