name: Test

on:
  push:
    branches:
      - main
    paths:
      - pyproject.toml
  workflow_dispatch:

concurrency: 
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  check-version:
    name: Check for version increment
    uses: ./.github/workflows/check-version.yml

  test:
    name: Build packages
    runs-on: ubuntu-latest
    needs: check-version
    steps:
    - name: Print Version Info
      run: |
        echo "#${{ needs.check_version.outputs.version }}#"
        echo "#${{ needs.check_version.outputs.version_change }}#"
        echo "#${{ needs.check_version.outputs.version_change == 'true' }}#"
